apiVersion: v1
kind: ConfigMap
metadata: { name: {{ include "igniteflux.name" . }}, namespace: {{ .Release.Namespace }} }
data:
  config.yaml: |
{{ merge (dict "git" (merge (dict "app_secret" .Values.appSecret) .Values.config.git)) .Values.config | toYaml | indent 4 }}
